# Generated by Django 5.2 on 2025-04-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_producto_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='total_stock',
            field=models.IntegerField(default=0),
        ),
    ]
